services:
  app:
    container_name: app

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=passworddb
      - POSTGRES_DB=equipmentdb
    volumes:
      - .:/workspace
    depends_on:
      - db
    # command: sleep infinity
  db:
    container_name: db
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: equipmentdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
